# Generated by Django 3.1.7 on 2021-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_fooditemfeedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemfeedback',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
