# Generated by Django 3.1.7 on 2021-03-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210318_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_price',
            field=models.FloatField(default=0),
        ),
    ]
