# Generated by Django 3.1.7 on 2021-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210319_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_category',
            field=models.CharField(choices=[('ST', 'Starters'), ('MC', 'Main Course'), ('DE', 'Dessert'), ('BR', 'Bread'), ('SN', 'Snacks')], default='MC', max_length=10),
        ),
    ]
