# Generated by Django 3.1.7 on 2021-03-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210320_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='num_ratings',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=3),
        ),
    ]
