# Generated by Django 3.1.7 on 2021-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210320_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
