# Generated by Django 3.1.7 on 2021-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210320_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_category',
            field=models.CharField(choices=[('MC', 'Main Course'), ('DE', 'Dessert'), ('BR', 'Bread'), ('SN', 'Snacks')], default='MC', max_length=10),
        ),
    ]
