# Generated by Django 3.1.7 on 2021-03-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('menu', '0007_auto_20210320_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='membership_discount',
            field=models.FloatField(default=0),
        ),
    ]
